language: python

python:
  - "2.7"

services:
  - mysql

install:
  - sudo apt-get purge -y mysql-common
  - wget https://raw.githubusercontent.com/frappe/bench/master/install_scripts/setup_frappe.sh
  - sudo bash setup_frappe.sh --skip-setup-bench --mysql-root-password travis --bench-branch develop
  - sudo pip install --upgrade pip
  - rm $TRAVIS_BUILD_DIR/.git/shallow
  - sudo service redis-server start
  - cd ~/ && bench init frappe-bench --frappe-path https://github.com/frappe/frappe.git --frappe-branch master
  - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site ~/frappe-bench/sites/


script:
  - cd ~/frappe-bench
  - bench get-app erpnext https://github.com/frappe/erpnext.git --branch master
  - bench get-app schools $TRAVIS_BUILD_DIR
  - bench use test_site
  - bench reinstall
  - bench --site test_site install-app erpnext
  - bench --site test_site install-app schools
  - bench start &
  - sleep 10
  - bench --verbose run-tests --driver Firefox

before_script:
  - mysql -e 'create database test_frappe'
  - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root -ptravis
